version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: sh -c "gem install webrick && git config --global --add safe.directory /srv/jekyll && bundle install && jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

